package models

// Artifact represents an output or intermediate file from a task
type Artifact struct {
	//unique identifier for the artifact generated by the agent. This identifier helps identify and assemble parts streamed by the agent
	ArtifactID string `json:"artifactId"`
	// Name is an optional name for the artifact
	Name string `json:"name,omitempty"`
	// Description is an optional description of the artifact
	Description string `json:"description,omitempty"`
	// Parts are the constituent parts of the artifact
	Parts []Part `json:"parts"`
	// Metadata is optional metadata associated with the artifact
	Metadata map[string]any `json:"metadata,omitempty"`
}

func (a *Artifact) EnsureRequiredFields() {
	if a == nil {
		return
	}
	if a.Parts == nil {
		a.Parts = []Part{}
	}
	for i := 0; i < len(a.Parts); i++ {
		if a.Parts[i].Kind == PartKindData && a.Parts[i].Data == nil {
			a.Parts[i].Data = make(map[string]any)
		}
	}
}
